# Generated by Django 5.1b1 on 2024-09-10 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAdvertisement',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('discounts', models.CharField(blank=True, max_length=255, null=True)),
                ('offers', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('guidelines', models.TextField()),
                ('links', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(upload_to='media/Adminads/thumbnail')),
                ('is_running', models.BooleanField(default=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_dashboard/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='user_dashboard/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
