# Generated by Django 5.1b1 on 2025-02-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_alter_adminadvertisement_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadvertisement',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='admin_ads/thumbnail/'),
        ),
    ]
