# Generated by Django 5.1b1 on 2024-09-19 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_delete_adminsettings_alter_adminnotification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadvertisement',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminadvertisement',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1), null=True),
        ),
        migrations.AlterField(
            model_name='adminadvertisement',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminadvertisement',
            name='id',
            field=models.CharField(default=None, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adminadvertisement',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='adminadvertisement',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/Adminads/thumbnail'),
        ),
        migrations.AlterField(
            model_name='adminadvertisement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
