# Generated by Django 5.1b1 on 2024-09-22 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
