# Generated by Django 5.1b1 on 2025-02-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_proof_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
