# Generated by Django 5.1b1 on 2025-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
